// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://xrwnftnfzwbrzijnbhfu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhyd25mdG5mendicnppam5iaGZ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI5MTE2MDYsImV4cCI6MjA3ODQ4NzYwNn0.9hB3813JqCwFwQaA_UDMxc4QJ4FDnqetlB6UnlKlhHY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);